# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('photo_url', models.CharField(max_length=500)),
                ('last_school', models.CharField(max_length=1000)),
            ],
        ),
    ]
