# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_hire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='current_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='dob',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('ND', 'Not Defined')], max_length=2),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='last_school',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Last School Name'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='lname',
            field=models.CharField(blank=True, max_length=200, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo_url',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume_url',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
