# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('R_hire', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidates',
            new_name='Candidate',
        ),
    ]
