# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('R_hire', '0002_auto_20160112_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='R_hire.Candidate')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('start_month', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CandidateDetails',
            fields=[
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='R_hire.Candidate')),
                ('summary', models.TextField()),
                ('current_location', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('ND', 'Not Defined')], default='M', max_length=1)),
                ('resume_url', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CandidatesLogin',
            fields=[
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='R_hire.Candidate')),
                ('email', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('created_tx', models.DateTimeField(verbose_name='Created at')),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='fname',
            field=models.CharField(max_length=200, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='lname',
            field=models.CharField(max_length=200, verbose_name='Last name'),
        ),
    ]
