# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('R_hire', '0003_auto_20160112_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('created_tx', models.DateTimeField(verbose_name='Created at')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='R_hire.Candidate', verbose_name='related candidate')),
            ],
            options={
                'db_table': 'candidate_login',
            },
        ),
        migrations.RemoveField(
            model_name='awards',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='candidateslogin',
            name='candidate',
        ),
        migrations.AddField(
            model_name='candidatedetails',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidatedetails',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='R_hire.Candidate', verbose_name='related candidate'),
        ),
        migrations.AlterModelTable(
            name='candidatedetails',
            table='candidate_details',
        ),
        migrations.DeleteModel(
            name='Awards',
        ),
        migrations.DeleteModel(
            name='CandidatesLogin',
        ),
    ]
