# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('R_hire', '0004_auto_20160112_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedetails',
            name='candidate',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='R_hire.Candidate', verbose_name='related candidate'),
        ),
        migrations.AlterField(
            model_name='candidatelogin',
            name='candidate',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='R_hire.Candidate', verbose_name='related candidate'),
        ),
        migrations.AlterModelTable(
            name='candidatedetails',
            table='R_hire_candidate_details',
        ),
        migrations.AlterModelTable(
            name='candidatelogin',
            table='R_hire_candidate_login',
        ),
    ]
