# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('R_hire', '0005_auto_20160112_0326'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidate',
            table='r_hire_candidate',
        ),
        migrations.AlterModelTable(
            name='candidatedetails',
            table='r_hire_candidate_details',
        ),
        migrations.AlterModelTable(
            name='candidatelogin',
            table='r_hire_candidate_login',
        ),
    ]
