# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('R_hire', '0006_auto_20160112_0328'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidate',
            table=None,
        ),
        migrations.AlterModelTable(
            name='candidatedetails',
            table='R_hire_candidate_details',
        ),
        migrations.AlterModelTable(
            name='candidatelogin',
            table='R_hire_candidate_login',
        ),
    ]
