# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('R_hire', '0007_auto_20160112_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedetails',
            name='candidate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='R_hire.Candidate', verbose_name='related candidate'),
        ),
        migrations.AlterField(
            model_name='candidatelogin',
            name='candidate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='R_hire.Candidate', verbose_name='related candidate'),
        ),
    ]
